Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "copyright", "credits" or "license()" for more information.
>>> bool('string'="string')
     
SyntaxError: EOL while scanning string literal
>>> bool((5>0) == False)
False
>>> bool((5>0) <= (1-1))
False
>>> bool((2>=9) <= (1-1))
True
>>> 6 == 7
False
>>> -3>= -1
False
>>> 3>= -1
True
>>> 'MEET' == 'meet'
False
>>> 'meet' == 'meet'
True
>>> a = 3
>>> b = 10
>>> a*4 == 2*b
False
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/indetation.py =======
hhhhhhhhhhhh
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/indetation.py =======
chocolate
hhhhhhhhhhhh
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/indetation.py =======
chocolate
hhhhhhhhhhhh
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/indetation.py =======
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/fruit_sorter.py ======
what fruit am i sorting hgisdgfjgh;fo
error! i do not recognize
>>> fghoglfgj
Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    fghoglfgj
NameError: name 'fghoglfgj' is not defined
>>> tthblsh
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    tthblsh
NameError: name 'tthblsh' is not defined
>>> agmd
Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    agmd
NameError: name 'agmd' is not defined
>>> wlk t36esh error
SyntaxError: invalid syntax
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py", line 4, in <module>
    if not(strarwberries > 39 and strawberries < 61):
NameError: name 'strarwberries' is not defined
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
not fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
not fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
not fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
not fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
not fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
not fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
not fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
fun
>>> 
====== RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtle_party.py ======
not fun
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
Traceback (most recent call last):
  File "<string>", line 8, in goto
  File "/usr/lib/python3.5/turtle.py", line 1776, in goto
    self._goto(Vec2D(x, y))
  File "/usr/lib/python3.5/turtle.py", line 3178, in _goto
    self._pencolor, self._pensize, top)
  File "/usr/lib/python3.5/turtle.py", line 545, in _drawline
    self.cv.coords(lineitem, *cl)
  File "<string>", line 1, in coords
  File "/usr/lib/python3.5/tkinter/__init__.py", line 2312, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".139673012927064"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py", line 5, in <module>
    turtle.goto(x,y)
  File "<string>", line 12, in goto
turtle.Terminator
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
Traceback (most recent call last):
  File "<string>", line 8, in goto
  File "/usr/lib/python3.5/turtle.py", line 1776, in goto
    self._goto(Vec2D(x, y))
  File "/usr/lib/python3.5/turtle.py", line 3178, in _goto
    self._pencolor, self._pensize, top)
  File "/usr/lib/python3.5/turtle.py", line 545, in _drawline
    self.cv.coords(lineitem, *cl)
  File "<string>", line 1, in coords
  File "/usr/lib/python3.5/tkinter/__init__.py", line 2312, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".139959446608472"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py", line 5, in <module>
    turtle.goto(x,y)
  File "<string>", line 12, in goto
turtle.Terminator
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
Traceback (most recent call last):
  File "<string>", line 8, in goto
  File "/usr/lib/python3.5/turtle.py", line 1776, in goto
    self._goto(Vec2D(x, y))
  File "/usr/lib/python3.5/turtle.py", line 3178, in _goto
    self._pencolor, self._pensize, top)
  File "/usr/lib/python3.5/turtle.py", line 545, in _drawline
    self.cv.coords(lineitem, *cl)
  File "<string>", line 1, in coords
  File "/usr/lib/python3.5/tkinter/__init__.py", line 2312, in coords
    self.tk.call((self._w, 'coords') + args))]
_tkinter.TclError: invalid command name ".139767577615048"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py", line 5, in <module>
    turtle.goto(x,y)
  File "<string>", line 12, in goto
turtle.Terminator
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py", line 14, in <module>
    turtle.left(360/num_pts)
  File "<string>", line 5, in left
turtle.Terminator
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======

======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py", line 14, in <module>
    turtle.left(360/num_pts)
  File "<string>", line 5, in left
turtle.Terminator
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py", line 14, in <module>
    turtle.goto(x,y)
  File "<string>", line 5, in goto
turtle.Terminator
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py", line 17, in <module>
    turtle.goto(x,y)
  File "<string>", line 5, in goto
turtle.Terminator
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py", line 26, in <module>
    turtle.goto(x,y)
  File "<string>", line 5, in goto
turtle.Terminator
>>> 
======= RESTART: /home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py =======
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
count
count
fizz
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
Traceback (most recent call last):
  File "/home/meet/forat19_lab4/meet2017y1lab4/turtleloop.py", line 26, in <module>
    turtle.goto(x,y)
  File "<string>", line 5, in goto
turtle.Terminator
>>> 
